# Generated by Django 2.1.2 on 2018-10-26 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='author',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='blog_type',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
