"""
Django settings for myweb project.

Generated by 'django-admin startproject' using Django 2.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
from .base import *

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '9m07cwa8lurllcx4d61w77cp%_r(bz57dtit&d$l^3@t3%dc$j'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'myweb_db',
        'USER': 'lius',
        'PASSWORD': '19931212',
        'HOST': 'localhost',
        'PORT': '3306',
    }
}
