# Generated by Django 2.1.2 on 2018-10-30 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='situation',
            name='user',
        ),
        migrations.DeleteModel(
            name='Situation',
        ),
    ]
