# Generated by Django 2.1.2 on 2018-10-29 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_time',
            new_name='created_time',
        ),
    ]
