# Generated by Django 2.1.2 on 2018-10-29 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_auto_20181029_2012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_time']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='parent_comment',
            new_name='parent',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='root_comment',
            new_name='root',
        ),
    ]
